/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class AppTest {

    @Test
    fun testFraccionToString() {
        val fraccion = Fraccion(3, 4)
        assertEquals("3/4", fraccion.toString())
    }

    @Test
    fun testDenominadorCero() {
        try {
            Fraccion(1, 0)
        } catch (e: IllegalArgumentException) {
            assertEquals("El denominador no puede ser cero", e.message)
        }
    }
}
